### ISSUE TITLE
Add unleash_project & unleash_project_user resource and data blocks

### ISSUE THREAD

**Issue by endk17** [philips-labs/terraform-provider-unleash#66]
🚀 Feature request

Description: 

- The ability to create, update and delete projects
- The ability to add, update and delete users (incl. user roles within a project) from a specific project

Labels: type: Enhancement

### Is your proposal related to a problem?

- Having the ability to manage projects and project users will allow for better instance management

### Describe the solution you'd like

```hcl
resource "unleash_user" "main" {
  name       = "Bob Joe"
  email      = "bob.joe@gmail.com"
  username   = "bobjoe"
  root_role  = "Viewer"
  send_email = true
}

resource "unleash_project" "main" {
  id          = "demo-project-id"
  name        = "demo-project-name"
  Description = "This is a demo project"
}

resource "unleash_project_user" "main" {
  user_id      = unleash_user.my_user.id
  project_id   = unleash_project.main.id
  project_role = "Editor"
}
```

I've opened a PR on the accompanying github repo where this provider utilises
ref: https://github.com/philips-labs/go-unleash-api/pull/15

**Comment by jdelucaa** [comment]
Hey 👋 
I just merged your contribution to the Go api. Thanks! 😄 
I will see if I can make some time this week to take a look on your request, I will keep you posted here.

**Comment by endk17** [comment]
> Hey 👋 I just merged your contribution to the Go api. Thanks! 😄 I will see if I can make some time this week to take a look on your request, I will keep you posted here.

Hi @jdelucaa 

Thanks for getting back to me on this, I've got time so I'll go ahead on start work on this one and see if I can get the PR in good shape for you to approve

PS: thanks for accepting the updates in https://github.com/philips-labs/go-unleash-api/pull/15

**Comment by jdelucaa** [comment]
> > Hey 👋 I just merged your contribution to the Go api. Thanks! 😄 I will see if I can make some time this week to take a look on your request, I will keep you posted here.
> 
> Hi @jdelucaa
> 
> Thanks for getting back to me on this, I'll go ahead and start work on this one and see if I can get the PR in good shape for you to approve
> 
> PS:
> 
> * thanks for accepting the updates in [Add support for additional project features go-unleash-api#15](https://github.com/philips-labs/go-unleash-api/pull/15)
> * Can you please draft a new release for go-unleash-api via https://github.com/philips-labs/go-unleash-api/releases running into issues when trying to use the latest tagged version

That would be awesome, thanks! 
I've just created a new release for the Go api, v1.0.3. Let me know it goes.

**Comment by jdelucaa** [comment]
Hi @endk17, 👋 
I haven't heard from you in a while, please let me know if you want me to take this over.  
Thanks 😄 🚀

**Comment by cschmatzler** [comment]
Hey @jdelucaa,
I'd be interested in this as well - let me know if I can support you in any way.

Cheers

**Comment by jdelucaa** [comment]
> Hey @jdelucaa, I'd be interested in this as well - let me know if I can support you in any way.
> 
> Cheers

Sure, let me look into this and come back to you.

**Comment by endk17** [comment]
> Hi @endk17, 👋 I haven't heard from you in a while, please let me know if you want me to take this over. Thanks 😄 🚀

Hi @jdelucaa 

Apologies I didn't get back to you earlier than now. Initially I was working with a hosted trial instance which didn't have the premium / enterprise features enabled

Recently this has changed and I could help out here with testing on a SaaS Enterprise instance

🤓

**Comment by jdelucaa** [comment]
> > Hi @endk17, 👋 I haven't heard from you in a while, please let me know if you want me to take this over. Thanks 😄 🚀
> 
> Hi @jdelucaa
> 
> Apologies I didn't get back to you earlier than now. Initially I was working with a hosted trial instance which didn't have the premium / enterprise features enabled
> 
> Recently this has changed and I could help out here with testing on a SaaS Enterprise instance
> 
> 🤓

hey @endk17 , your help with testing would be very appreciated, I don't have access to the enterprise instance so I am blindly implementing it. 😞 

Would you be so kind to test the `unleash-project` resource I implemented in #71? If that is working I can already deliver it and start working on the `unleash-project-user` resource in the meantime.

Please let me know if u need help building the provider to test it locally. You can download my branch and run `go build .`  from the root to get the executable, then you can copy and paste it to the terraform.d folder and run `terraform init`.

If you are on Windows, you can copy the executable to (you will have to create some of these folders):
~\AppData\Roaming\terraform.d\plugins\terraform.example.com\local\unleash\0.0.1\windows_amd64

And configure the `required_providers` block like so:
```
terraform {
  required_providers {
    unleash = {
      version = "0.0.1"
      source  = "terraform.example.com/local/unleash"
    }
  }
}
```

Then `terraform init`.

Buuuut, it would already help if you could make sure the API client is working as expected :)
Thank you!

**Comment by endk17** [comment]
Hi @jdelucaa 

Sorry I have been able to get the time to complete the E2E testing. Was able to run the `go build` ok but `terraform init` was giving some errors. I just didn't get the time to follow up on resolving each of them

Thanks for letting me know about the official provider that is being worked on by the Unleash team
So maybe it's ok to close this issue now

Best wishes and luck for the future 🍀 🍀 🍀

**Comment by jdelucaa** [comment]
@endk17 Thanks!😄
Closing this issue now.
